### PR TITLE
add ignore flag

### PR DESCRIPTION
**Pull request by yordaa-me**

### CODE REVIEW

**Review by andrewjlowery — APPROVED** [review]

**Comment by cristim** [comment]
hi @dannyibishev @andrewjlowery I'm curious what are you trying to achieve with this change, is it something that would potentially be upstreamed? would it be useful to other AutoSpotting users installing it from Terraform?

**Comment by yordaa-me** [comment]
Hi @cristim

This was required for our own release pipeline use case.

Why this was useful to us:

#### The problem we want to resolve
During a release to one of our test environments (which has autospotting enabled). We identified issues caused by auto spotting. Essentially, instances were being taken offline while our pipeline would be in the middle of applying config. This invalidated our pipeline run.

We wanted to solve this issue by temporarily disabling the cloudwatch rule that targets the auto spotting lambda during the start of the pipeline and re-enable it at the end.

#### Our Use case with the above.
- Within our release pipeline. We would disable the cloud watch rule as an automated pre-requisite step.
- During the pipeline, Terraform modules could be ran in if enabled during the run. This had the potential of running the module reference for auto spotting which then would re-enable this rule. This defeats the purpose of our use case. Hence the ignore flag. 
- The cloudwatch rule is *_*always**_ enabled again at the end of the pipeline as an automated post-requisite.

I hope that clears things up. I can appreciate that not everyone would want to do this, which is why I haven't created a PR back to the main Repo.

**Comment by cristim** [comment]
Thanks for the clarification!

For such use case AutoSpotting has a cron schedule that allows you to disable it during office hours. 

Another probably better way might be to toggle the Autoscaling Group tag of the environment under test or simply tagging it with the spot-enabled=true only after the test completed. The benefit is that AutoSpotting can then still handle other Autoscaling groups in your account.

**Comment by yordaa-me** [comment]
Thanks for the suggestion. 

@andrewjlowery please see the above :) ^

**Pull request merged**
